layout_spectrum: 0.4483034
typography_spectrum: 0.7275985
color:
  saturation: 0.537898
  brandStrength: 0.6262291
  lightness: 0
  rhythmicContrast: 0.9300439
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Sandeep Sangaru
